[package]
authors = ["Ryan Kurte <ryankurte@gmail.com>"]
description = "Driver for the Semtec sx1280 2.4GHz RF IC"
repository = "https://github.com/rust-iot/rust-radio-sx128x"
license = "MPL-2.0"
name = "radio-sx128x"
version = "0.18.0"
edition = "2018"

[features]

defmt = []
patch-unknown-state = []

default = [ "defmt", "patch-unknown-state" ]

[dependencies]


bitflags = "1.0.4"
log = { version = "0.4.17", default_features = false }
strum = { version = "0.24.0", default_features = false, features = [ "derive" ] }

crc16 = { version = "0.4.0", optional = true }
hex = { version = "0.4.2", optional = true }

humantime = { version = "2.0.1", optional = true }
thiserror = { version = "1.0.30", optional = true }
failure = { version = "0.1.7", features = [ "derive" ], default-features = false }

tracing = { version = "0.1.34", optional = true }
tracing-subscriber = { version = "0.2.16", optional = true }
defmt = "0.3"

[dev-dependencies]
color-backtrace = "0.5.0"
toml = "0.5.8"